### ISSUE TITLE
在Mac上我试了一下,很不错的小工具,提个bug

### ISSUE THREAD

**Issue by WanDa1993** [shadon178/FloatWord#1]
单词切换的时候,会出现重影
![image](https://user-images.githubusercontent.com/16666953/53349025-2956c080-3957-11e9-9c96-d14774bc2550.png)

**Comment by shadon178** [comment]
不好意思，暂时没有mac电脑，所以对mac的支持不好。

**Comment by shadon178** [comment]
> 单词切换的时候,会出现重影
> ![image](https://user-images.githubusercontent.com/16666953/53349025-2956c080-3957-11e9-9c96-d14774bc2550.png)

没有mac电脑，因此对mac的支持不是很好。
